// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jlbomgmlzzvplzlodhwl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpsYm9tZ21senp2cGx6bG9kaHdsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAyNDY3MjksImV4cCI6MjA3NTgyMjcyOX0.8hMUEmNfdG0v1WaRxzjbLLwfOvhFpR03HAaZ4wikwU0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});